version: '3.9'

services:
  ms_users:
    container_name: ms_users
    build: .
    ports:
    - 8080:5000
    volumes:
    - ./:/app
    env_file:
    - .env
    depends_on:
    - ms_db
    - ms_redis
    networks:
    - msUsersNetwork

  ms_db:
    container_name: ms_db
    image: postgres
    ports:
    - 5432:5432
    volumes:
    - msUsersDbVolume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ms_users
      POSTGRES_USER: ms_users
      POSTGRES_PASSWORD: secret
    networks:
    - msUsersNetwork

  ms_redis:
    container_name: ms_redis
    image: redis:6-alpine
    ports:
      - 6379:6379
    networks:
      - msUsersNetwork


volumes:
  msUsersDbVolume:
    driver: local


networks:
  msUsersNetwork:
    driver: "bridge"
