version: '3.9'

services:
  ms_aq_users:
    container_name: ms_aq_users
    build: .
    ports:
    - 8080:5000
    volumes:
    - ./:/app
    env_file:
    - .env
    depends_on:
    - ms_aq_db
    - ms_aq_redis
    networks:
    - aqUsersNetwork

  ms_aq_celery:
    container_name: ms_aq_celery
    build: .
    volumes:
    - ./:/app
    env_file:
    - .env
    environment:
    - APP_ENV=celery
    depends_on:
    - ms_aq_db
    - ms_aq_redis
    networks:
    - aqUsersNetwork

  ms_aq_db:
    container_name: ms_aq_db
    image: postgres
    ports:
    - 5432:5432
    volumes:
    - aqUsersDbVolume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ms_users
      POSTGRES_USER: ms_users
      POSTGRES_PASSWORD: secret
    networks:
    - aqUsersNetwork

  ms_aq_redis:
    container_name: ms_aq_redis
    image: redis:6-alpine
    ports:
      - 6379:6379
    networks:
      - aqUsersNetwork


volumes:
  aqUsersDbVolume:
    driver: local


networks:
  aqUsersNetwork:
    driver: "bridge"
