"""empty message

Revision ID: 5d60ca96ac52
Revises: b482a63d75b4
Create Date: 2022-08-16 20:33:16.176980

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d60ca96ac52'
down_revision = 'b482a63d75b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('entity_birth', sa.String(length=255), nullable=True))
    op.add_column('profile', sa.Column('grade', sa.String(length=60), nullable=True))
    op.add_column('profile', sa.Column('marital_status', sa.String(length=60), nullable=True))
    op.add_column('profile', sa.Column('department', sa.String(length=60), nullable=True))
    op.add_column('profile', sa.Column('street', sa.String(length=255), nullable=True))
    op.add_column('profile', sa.Column('exterior', sa.String(length=6), nullable=True))
    op.add_column('profile', sa.Column('interior', sa.String(length=6), nullable=True))
    op.add_column('profile', sa.Column('neighborhood', sa.String(length=255), nullable=True))
    op.add_column('profile', sa.Column('zip', sa.String(length=5), nullable=True))
    op.add_column('profile', sa.Column('monthly_expenditure', sa.Float(), nullable=True))
    op.add_column('profile', sa.Column('income', sa.Float(), nullable=True))
    op.add_column('profile', sa.Column('income_family', sa.Float(), nullable=True))
    op.add_column('profile', sa.Column('count_home', sa.Integer(), nullable=True))
    op.add_column('profile', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('profile', sa.Column('type_activity', sa.String(length=255), nullable=True))
    op.add_column('profile', sa.Column('position', sa.String(length=255), nullable=True))
    op.add_column('profile', sa.Column('time_activity_year', sa.Integer(), nullable=True))
    op.add_column('profile', sa.Column('time_activity_month', sa.Integer(), nullable=True))
    op.add_column('profile', sa.Column('personal_references', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'personal_references')
    op.drop_column('profile', 'time_activity_month')
    op.drop_column('profile', 'time_activity_year')
    op.drop_column('profile', 'position')
    op.drop_column('profile', 'type_activity')
    op.drop_column('profile', 'company_name')
    op.drop_column('profile', 'count_home')
    op.drop_column('profile', 'income_family')
    op.drop_column('profile', 'income')
    op.drop_column('profile', 'monthly_expenditure')
    op.drop_column('profile', 'zip')
    op.drop_column('profile', 'neighborhood')
    op.drop_column('profile', 'interior')
    op.drop_column('profile', 'exterior')
    op.drop_column('profile', 'street')
    op.drop_column('profile', 'department')
    op.drop_column('profile', 'marital_status')
    op.drop_column('profile', 'grade')
    op.drop_column('profile', 'entity_birth')
    # ### end Alembic commands ###
