name: Test application

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt;
          pip install -e .

      - name: Test with unittest
        run: |
          coverage run -m pytest
          coverage report
